const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.LOS,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Follow,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.SetEnabled,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{"8Direções": 0},
	{player: 0},
	{fundo: 0},
	{CampoDeVisão: 0},
	{robo: 0},
	{Teclado: 0},
	{Projétil: 0},
	{laser: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{paredeInvisivel: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto: 0},
	{Sprite5: 0},
	{Seguir: 0},
	{missel: 0},
	{Sprite6: 0},
	{Texto2: 0},
	{direção: 0},
	{atirando: 0},
	{vidaBoss: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	fundo: class extends self.ISpriteInstance {},
	robo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	laser: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	paredeInvisivel: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	missel: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {}
}